title: "Excalidraw"
description: "Virtual whiteboard for sketching hand-drawn like diagrams"
homepage: "https://excalidraw.com/"
live_url: "https://excalidraw.com/"
license: MIT
tags:
  - office
  - drawing
  - whiteboard
  - diagram

source:
  type: git
  url: "https://github.com/excalidraw/excalidraw"
  ref: "v.*"
  ref_type: tag_pattern

docker_image: "node:22"
